/**
 * @file persistence_corpus_test.cpp
 * @brief Load every pinned persistence fixture through the real read paths
 *
 * The fixtures under corpus/ are checked-in bytes. This file only ever reads
 * them: nothing here regenerates a fixture, because a fixture regenerated by
 * the code under test would prove nothing about backward compatibility.
 *
 * A failure in this file means an artifact an earlier release could write is
 * no longer readable, which is an externally visible compatibility break.
 */

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>

#include "compat/corpus_manifest.h"
#include "config/config.h"
#include "index/index.h"
#include "server/dump_config_validator.h"
#include "storage/document_store.h"
#include "storage/dump_format.h"
#include "storage/dump_format_v1.h"
#include "storage/dump_format_v2.h"
#include "utils/error.h"

namespace {

using mygram::utils::ErrorCode;
using mygramdb::index::Index;
using mygramdb::storage::DocumentStore;
using mygramdb::storage::FilterValue;

namespace corpus = mygramdb::compat;

/// Read a checked-in fixture verbatim. Never writes, never regenerates.
std::string ReadFixture(std::string_view name) {
  const std::filesystem::path path = std::filesystem::path(MYGRAMDB_COMPAT_CORPUS_DIR) / std::string(name);
  std::ifstream stream(path, std::ios::binary);
  EXPECT_TRUE(stream) << "missing corpus fixture: " << path;
  return std::string((std::istreambuf_iterator<char>(stream)), std::istreambuf_iterator<char>());
}

std::string FixturePath(std::string_view name) {
  return (std::filesystem::path(MYGRAMDB_COMPAT_CORPUS_DIR) / std::string(name)).string();
}

/// A table's restore targets, kept together so a load can be asserted on both.
struct RestoreTargets {
  std::unique_ptr<Index> index;
  std::unique_ptr<DocumentStore> doc_store;

  std::unordered_map<std::string, std::pair<Index*, DocumentStore*>> Contexts(std::string_view table_name) {
    std::unordered_map<std::string, std::pair<Index*, DocumentStore*>> contexts;
    contexts.emplace(std::string(table_name), std::make_pair(index.get(), doc_store.get()));
    return contexts;
  }
};

RestoreTargets MakeCorpusTargets() {
  return RestoreTargets{corpus::MakeCorpusIndex(), std::make_unique<DocumentStore>()};
}

/// Assert the index holds exactly the terms and posting lists the corpus pins.
void ExpectCorpusIndexContent(const Index& index) {
  const auto terms = corpus::CorpusTerms();
  EXPECT_EQ(index.TermCount(), terms.size());
  for (const auto& term : terms) {
    EXPECT_EQ(index.Count(term.term), term.doc_ids.size()) << "term: " << term.term;
    EXPECT_EQ(index.SearchOr({std::string(term.term)}), term.doc_ids) << "term: " << term.term;
  }
  // A term present in two posting lists intersects to the one document in both.
  EXPECT_EQ(index.SearchAnd({"he", "ll"}), std::vector<mygramdb::DocId>({1}));
}

/**
 * @brief Assert the document store holds exactly what the corpus pins.
 *
 * @param store Loaded store
 * @param version Document store format version the payload declared, which
 *                decides whether per-document texts are expected at all
 */
void ExpectCorpusDocStoreContent(const DocumentStore& store, uint32_t version) {
  const auto documents = corpus::CorpusDocuments();
  ASSERT_EQ(store.Size(), documents.size());

  for (const auto& document : documents) {
    EXPECT_EQ(store.GetDocId(document.primary_key), std::optional<mygramdb::DocId>(document.doc_id));
    EXPECT_EQ(store.GetPrimaryKey(document.doc_id), std::optional<std::string>(std::string(document.primary_key)));

    if (version >= 2) {
      EXPECT_EQ(store.GetNormalizedText(document.doc_id),
                std::optional<std::string>(std::string(document.normalized_text)));
    } else {
      EXPECT_FALSE(store.GetNormalizedText(document.doc_id).has_value());
    }
    if (version >= 3) {
      EXPECT_EQ(store.GetOriginalText(document.doc_id),
                std::optional<std::string>(std::string(document.original_text)));
    } else {
      EXPECT_FALSE(store.GetOriginalText(document.doc_id).has_value());
    }
  }

  const auto int_filter = store.GetFilterValue(1, corpus::kIntFilterName);
  ASSERT_TRUE(int_filter.has_value());
  ASSERT_TRUE(std::holds_alternative<int32_t>(*int_filter));
  EXPECT_EQ(std::get<int32_t>(*int_filter), corpus::kIntFilterValue);

  const auto string_filter = store.GetFilterValue(2, corpus::kStringFilterName);
  ASSERT_TRUE(string_filter.has_value());
  ASSERT_TRUE(std::holds_alternative<std::string>(*string_filter));
  EXPECT_EQ(std::get<std::string>(*string_filter), corpus::kStringFilterValue);

  EXPECT_FALSE(store.GetFilterValue(3, corpus::kIntFilterName).has_value());
  EXPECT_FALSE(store.GetFilterValue(3, corpus::kStringFilterName).has_value());
}

// ============================================================================
// Index payloads
// ============================================================================

struct IndexFixture {
  std::string_view file;
  uint32_t version;
};

class IndexPayloadCorpusTest : public ::testing::TestWithParam<IndexFixture> {};

TEST_P(IndexPayloadCorpusTest, LoadsWithTheRecordedTerms) {
  const IndexFixture fixture = GetParam();
  std::istringstream stream(ReadFixture(fixture.file));

  auto index = corpus::MakeCorpusIndex();
  auto result = index->LoadFromStream(stream);
  ASSERT_TRUE(result.has_value()) << "index format version " << fixture.version
                                  << " is no longer readable: " << result.error().message();
  ExpectCorpusIndexContent(*index);
}

INSTANTIATE_TEST_SUITE_P(AcceptedVersions, IndexPayloadCorpusTest,
                         ::testing::Values(IndexFixture{corpus::kIndexV1File, 1}, IndexFixture{corpus::kIndexV2File, 2},
                                           IndexFixture{corpus::kIndexV3File, 3},
                                           IndexFixture{corpus::kIndexV4File, 4}),
                         [](const ::testing::TestParamInfo<IndexFixture>& info) {
                           return "V" + std::to_string(info.param.version);
                         });

TEST(IndexPayloadCorpusRejectionTest, VersionAboveTheCeilingIsRefused) {
  std::istringstream stream(ReadFixture(corpus::kIndexV5File));
  auto index = corpus::MakeCorpusIndex();

  auto result = index->LoadFromStream(stream);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageVersionMismatch);
  EXPECT_NE(result.error().message().find("Unsupported index format version"), std::string::npos);
}

// ============================================================================
// Document store payloads
// ============================================================================

struct DocStoreFixture {
  std::string_view file;
  uint32_t version;
};

class DocStorePayloadCorpusTest : public ::testing::TestWithParam<DocStoreFixture> {};

TEST_P(DocStorePayloadCorpusTest, LoadsWithTheRecordedDocuments) {
  const DocStoreFixture fixture = GetParam();
  std::istringstream stream(ReadFixture(fixture.file));

  DocumentStore store;
  std::string gtid;
  auto result = store.LoadFromStream(stream, &gtid);
  ASSERT_TRUE(result.has_value()) << "document store format version " << fixture.version
                                  << " is no longer readable: " << result.error().message();
  EXPECT_EQ(gtid, corpus::kGtid);
  ExpectCorpusDocStoreContent(store, fixture.version);
}

INSTANTIATE_TEST_SUITE_P(AcceptedVersions, DocStorePayloadCorpusTest,
                         ::testing::Values(DocStoreFixture{corpus::kDocStoreV1File, 1},
                                           DocStoreFixture{corpus::kDocStoreV2File, 2},
                                           DocStoreFixture{corpus::kDocStoreV3File, 3}),
                         [](const ::testing::TestParamInfo<DocStoreFixture>& info) {
                           return "V" + std::to_string(info.param.version);
                         });

TEST(DocStorePayloadCorpusRejectionTest, VersionAboveTheCeilingIsRefused) {
  std::istringstream stream(ReadFixture(corpus::kDocStoreV4File));

  DocumentStore store;
  auto result = store.LoadFromStream(stream);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageCorrupted);
  EXPECT_NE(result.error().message().find("Unsupported document store file version"), std::string::npos);
}

// ============================================================================
// Dump containers
// ============================================================================

struct DumpFixture {
  std::string_view file;
  const char* name;
  /// Document store version embedded in the table section.
  uint32_t docstore_version;
  /// MySQL source server UUID the dump is expected to yield, empty when none.
  std::string_view source_server_uuid;
  /// memory.verify_text the config section is expected to yield.
  std::string_view verify_text;
};

class DumpContainerCorpusTest : public ::testing::TestWithParam<DumpFixture> {};

TEST_P(DumpContainerCorpusTest, LoadsWithTheRecordedContent) {
  const DumpFixture fixture = GetParam();

  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);

  std::string gtid;
  mygramdb::config::Config loaded_config;
  // Pre-seed the UUID so a reader that never writes it is distinguishable from
  // one that writes an empty string.
  std::string source_server_uuid = "not-populated-by-the-reader";

  auto result = mygramdb::storage::dump_v2::ReadDump(FixturePath(fixture.file), gtid, loaded_config, contexts, nullptr,
                                                     nullptr, nullptr, {}, {}, &source_server_uuid);
  ASSERT_TRUE(result.has_value()) << fixture.name << " is no longer readable: " << result.error().message();

  EXPECT_EQ(gtid, corpus::kGtid);
  EXPECT_EQ(source_server_uuid, fixture.source_server_uuid);
  EXPECT_EQ(loaded_config.memory.verify_text, fixture.verify_text);
  EXPECT_EQ(loaded_config.mysql.host, corpus::kMysqlHost);
  EXPECT_EQ(loaded_config.mysql.port, corpus::kMysqlPort);
  EXPECT_EQ(loaded_config.mysql.database, corpus::kMysqlDatabase);
  ASSERT_EQ(loaded_config.tables.size(), 1U);
  EXPECT_EQ(loaded_config.tables[0].name, corpus::kTableName);
  EXPECT_EQ(loaded_config.tables[0].ngram_size, corpus::kNgramSize);
  EXPECT_EQ(loaded_config.tables[0].kanji_ngram_size, corpus::kKanjiNgramSize);

  ExpectCorpusIndexContent(*targets.index);
  ExpectCorpusDocStoreContent(*targets.doc_store, fixture.docstore_version);
}

INSTANTIATE_TEST_SUITE_P(
    AcceptedVersions, DumpContainerCorpusTest,
    ::testing::Values(
        // Container V1, compatibility metadata version 1, index V1, docstore V1.
        DumpFixture{corpus::kDumpV1MetaV1File, "container V1 with compatibility metadata version 1", 1, "",
                    corpus::kVerifyText},
        // Container V1 as WriteDumpV1 emits it: metadata version 2, index V4, docstore V3.
        DumpFixture{corpus::kDumpV1MetaV2File, "container V1 from WriteDumpV1", 3, "", corpus::kVerifyText},
        // Container V2 carrying index V3 and docstore V2, versions no writer emits.
        DumpFixture{corpus::kDumpV2LegacyPayloadsFile, "container V2 with legacy embedded payloads", 2,
                    corpus::kSourceServerUuid, corpus::kVerifyText},
        // Container V2 as WriteDumpV2 emits it.
        DumpFixture{corpus::kDumpV2CurrentFile, "container V2 from WriteDumpV2", 3, corpus::kSourceServerUuid,
                    corpus::kVerifyText}),
    [](const ::testing::TestParamInfo<DumpFixture>& info) {
      std::string suite_name(info.param.file);
      suite_name = suite_name.substr(0, suite_name.find('.'));
      for (char& character : suite_name) {
        if (character == '_') {
          character = 'X';
        }
      }
      return suite_name;
    });

TEST(DumpContainerCorpusRejectionTest, VersionAboveTheCeilingIsRefused) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result = mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV3File), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageDumpReadError);
  EXPECT_NE(result.error().message().find("Unsupported dump version"), std::string::npos);
}

TEST(DumpContainerCorpusRejectionTest, CompatibilityMetadataVersionAboveTheCeilingIsRefused) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result =
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpMetaV3File), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageVersionMismatch);
  EXPECT_NE(result.error().message().find("Unsupported compatibility metadata version"), std::string::npos);
}

TEST(DumpContainerCorpusRejectionTest, DirectV2ReaderRefusesAV1Container) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result =
      mygramdb::storage::dump_v2::ReadDumpV2(FixturePath(corpus::kDumpV1MetaV1File), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageDumpReadError);
  EXPECT_NE(result.error().message().find("Not a V2 dump file"), std::string::npos);
}

TEST(DumpContainerCorpusRejectionTest, DirectV1ReaderRefusesAV2Container) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result =
      mygramdb::storage::dump_v1::ReadDumpV1(FixturePath(corpus::kDumpV2CurrentFile), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageVersionMismatch);
}

// ============================================================================
// The container layer accepts a V1 dump that the server layer then refuses
// ============================================================================

TEST(DumpContainerV1ServerRefusalTest, ContainerLayerLoadsButRecordsNoSourceServerUuid) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;
  std::string source_server_uuid = "not-populated-by-the-reader";

  auto result = mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV1MetaV1File), gtid, loaded_config,
                                                     contexts, nullptr, nullptr, nullptr, {}, {}, &source_server_uuid);
  ASSERT_TRUE(result.has_value()) << result.error().message();
  // The dispatcher clears the caller's buffer and the V1 reader has no way to
  // fill it, so a V1 dump can never carry a source server UUID.
  EXPECT_TRUE(source_server_uuid.empty());
}

TEST(DumpContainerV1ServerRefusalTest, StartupRestoreValidatorRefusesADumpWithoutSourceServerUuid) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;
  std::string source_server_uuid = "not-populated-by-the-reader";

  // The rule startup restore applies: a dump that records no MySQL source
  // server UUID is refused, whatever the container layer made of it.
  auto validator = [&source_server_uuid](const mygramdb::config::Config&,
                                         const std::string&) -> mygram::utils::Expected<void, mygram::utils::Error> {
    if (source_server_uuid.empty()) {
      return mygram::utils::MakeUnexpected(mygram::utils::MakeError(ErrorCode::kStorageVersionMismatch,
                                                                    "dump does not record its MySQL source server "
                                                                    "UUID"));
    }
    return {};
  };

  auto result =
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV1MetaV1File), gtid, loaded_config, contexts,
                                           nullptr, nullptr, nullptr, validator, {}, &source_server_uuid);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageVersionMismatch);

  // The refusal happens before any live table state is replaced.
  EXPECT_EQ(targets.index->TermCount(), 0U);
  EXPECT_EQ(targets.doc_store->Size(), 0U);
}

TEST(DumpContainerV1ServerRefusalTest, MetadataVersion2DumpSatisfiesTheSameValidator) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;
  std::string source_server_uuid;

  auto validator = [&source_server_uuid](const mygramdb::config::Config&,
                                         const std::string&) -> mygram::utils::Expected<void, mygram::utils::Error> {
    if (source_server_uuid.empty()) {
      return mygram::utils::MakeUnexpected(mygram::utils::MakeError(ErrorCode::kStorageVersionMismatch,
                                                                    "dump does not record its MySQL source server "
                                                                    "UUID"));
    }
    return {};
  };

  auto result =
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV2CurrentFile), gtid, loaded_config, contexts,
                                           nullptr, nullptr, nullptr, validator, {}, &source_server_uuid);
  ASSERT_TRUE(result.has_value()) << result.error().message();
  EXPECT_EQ(source_server_uuid, corpus::kSourceServerUuid);
}

// ============================================================================
// Configuration compatibility of the loaded config sections
// ============================================================================

TEST(DumpConfigCompatibilityTest, MetadataBearingDumpMatchesAServerRunningTheSameSettings) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  ASSERT_TRUE(
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV2CurrentFile), gtid, loaded_config, contexts)
          .has_value());

  const auto live_config = corpus::CorpusConfig();
  EXPECT_FALSE(mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config).has_value());
}

TEST(DumpConfigCompatibilityTest, DivergingNormalizationIsRefusedByTheSharedCheck) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  ASSERT_TRUE(
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV2CurrentFile), gtid, loaded_config, contexts)
          .has_value());

  auto live_config = corpus::CorpusConfig();
  live_config.memory.normalize.lower = !corpus::kNormalizeLower;
  const auto mismatch = mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config);
  ASSERT_TRUE(mismatch.has_value());
  EXPECT_NE(mismatch->find("memory.normalize.lower"), std::string::npos);
}

// ============================================================================
// Dumps written by earlier releases
//
// These four files came out of the release trees named in their file names,
// through that release's own dump writer, so they carry that release's
// defaults rather than the manifest's settings. They are the only fixtures in
// the corpus whose bytes no current code path can reproduce.
// ============================================================================

struct ReleaseDumpFixture {
  std::string_view file;
  const char* release;
  /// memory.verify_text the config section yields. Releases that predate the
  /// compatibility metadata record nothing, which reads back as empty.
  std::string_view verify_text;
  /// Whether the document store payload carries per-document normalized text.
  bool has_normalized_text;
};

class ReleaseDumpCorpusTest : public ::testing::TestWithParam<ReleaseDumpFixture> {};

TEST_P(ReleaseDumpCorpusTest, StillLoadsWithItsRecordedContent) {
  const ReleaseDumpFixture fixture = GetParam();

  // Every one of these releases wrote its index payload from a default-
  // configured Index, so the restore target has to be one too.
  RestoreTargets targets{std::make_unique<Index>(), std::make_unique<DocumentStore>()};
  auto contexts = targets.Contexts(corpus::kTableName);

  std::string gtid;
  mygramdb::config::Config loaded_config;
  std::string source_server_uuid = "not-populated-by-the-reader";

  auto result = mygramdb::storage::dump_v2::ReadDump(FixturePath(fixture.file), gtid, loaded_config, contexts, nullptr,
                                                     nullptr, nullptr, {}, {}, &source_server_uuid);
  ASSERT_TRUE(result.has_value()) << "a dump written by " << fixture.release
                                  << " is no longer readable: " << result.error().message();

  EXPECT_EQ(gtid, corpus::kGtid);
  EXPECT_EQ(loaded_config.mysql.host, corpus::kMysqlHost);
  EXPECT_EQ(loaded_config.mysql.port, corpus::kMysqlPort);
  EXPECT_EQ(loaded_config.mysql.database, corpus::kMysqlDatabase);
  ASSERT_EQ(loaded_config.tables.size(), 1U);
  EXPECT_EQ(loaded_config.tables[0].name, corpus::kTableName);
  EXPECT_EQ(loaded_config.tables[0].ngram_size, 2);
  EXPECT_EQ(loaded_config.memory.verify_text, fixture.verify_text);

  // No release up to and including v1.9.0 recorded a MySQL source server UUID.
  EXPECT_TRUE(source_server_uuid.empty());

  // The three indexed documents were "hello", "hello world" and "helo".
  EXPECT_EQ(targets.index->SearchOr({"he"}), std::vector<mygramdb::DocId>({1, 2, 3}));
  EXPECT_EQ(targets.index->SearchOr({"ll"}), std::vector<mygramdb::DocId>({1, 2}));
  EXPECT_EQ(targets.index->SearchOr({"wo"}), std::vector<mygramdb::DocId>({2}));
  EXPECT_EQ(targets.index->SearchAnd({"he", "wo"}), std::vector<mygramdb::DocId>({2}));

  ASSERT_EQ(targets.doc_store->Size(), 3U);
  EXPECT_EQ(targets.doc_store->GetDocId("alpha"), std::optional<mygramdb::DocId>(1));
  EXPECT_EQ(targets.doc_store->GetDocId("beta"), std::optional<mygramdb::DocId>(2));
  EXPECT_EQ(targets.doc_store->GetDocId("gamma"), std::optional<mygramdb::DocId>(3));
  EXPECT_EQ(targets.doc_store->GetPrimaryKey(2), std::optional<std::string>("beta"));

  if (fixture.has_normalized_text) {
    EXPECT_EQ(targets.doc_store->GetNormalizedText(2), std::optional<std::string>("hello world"));
  } else {
    EXPECT_FALSE(targets.doc_store->GetNormalizedText(2).has_value());
  }
}

INSTANTIATE_TEST_SUITE_P(EarlierReleases, ReleaseDumpCorpusTest,
                         ::testing::Values(ReleaseDumpFixture{corpus::kReleaseV154File, "v1.5.4", "", false},
                                           ReleaseDumpFixture{corpus::kReleaseV161File, "v1.6.1", "", false},
                                           ReleaseDumpFixture{corpus::kReleaseV190File, "v1.9.0", corpus::kVerifyText,
                                                              true}),
                         [](const ::testing::TestParamInfo<ReleaseDumpFixture>& info) {
                           std::string name(info.param.release);
                           for (char& character : name) {
                             if (character == '.') {
                               character = '_';
                             }
                           }
                           return name;
                         });

/**
 * @brief A dump written by v1.3.2 does not load, and this records that.
 *
 * Releases up to and including v1.5.3 left the V1 header's header_size field
 * at zero; v1.5.4 began writing it, and a later release added a read-time
 * check that the field equals 32 plus the GTID length. The check refuses
 * anything those earlier releases wrote, so their dumps are unreadable by the
 * current code even though the container version is accepted.
 *
 * This assertion states what the code does today. It is not a statement that
 * the behavior is correct: if the read path is ever made to accept a zero
 * header_size again, this test is the thing that has to change.
 */
TEST(ReleaseDumpCorpusRejectionTest, DumpWrittenByV132IsRefusedForItsZeroHeaderSize) {
  RestoreTargets targets{std::make_unique<Index>(), std::make_unique<DocumentStore>()};
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result =
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kReleaseV132File), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value()) << "a v1.3.2 dump now loads; the corpus expectation is stale";
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageDumpReadError);
  EXPECT_NE(result.error().message().find("Invalid V1 header size"), std::string::npos)
      << "unexpected refusal reason: " << result.error().message();

  // Nothing was applied to the live objects.
  EXPECT_EQ(targets.index->TermCount(), 0U);
  EXPECT_EQ(targets.doc_store->Size(), 0U);
}

TEST(ReleaseDumpConfigCompatibilityTest, DumpsPredatingCompatibilityMetadataLoadOnlyIntoVerifyTextOff) {
  RestoreTargets targets{std::make_unique<Index>(), std::make_unique<DocumentStore>()};
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  ASSERT_TRUE(mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kReleaseV154File), gtid, loaded_config, contexts)
                  .has_value());
  ASSERT_TRUE(loaded_config.memory.verify_text.empty());

  // Isolate the verify_text rule: everything else the shared check compares is
  // taken from the dump, so only the missing metadata can cause a mismatch.
  auto live_config = loaded_config;
  live_config.memory.verify_text = "off";
  EXPECT_FALSE(mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config).has_value());

  live_config.memory.verify_text = "all";
  const auto mismatch = mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config);
  ASSERT_TRUE(mismatch.has_value());
  EXPECT_NE(mismatch->find("verify_text"), std::string::npos);
}

}  // namespace
