/**
 * @file persistence_corpus_test.cpp
 * @brief Load every pinned persistence fixture through the real read paths
 *
 * The fixtures under corpus/ are checked-in bytes. This file only ever reads
 * them: nothing here regenerates a fixture, because a fixture regenerated by
 * the code under test would prove nothing about backward compatibility.
 *
 * A failure in this file means an artifact an earlier release could write is
 * no longer readable, which is an externally visible compatibility break.
 */

#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <string_view>
#include <unordered_map>
#include <utility>
#include <vector>

#include "compat/corpus_manifest.h"
#include "config/config.h"
#include "index/index.h"
#include "server/dump_config_validator.h"
#include "storage/document_store.h"
#include "storage/dump_format.h"
#include "storage/dump_format_v1.h"
#include "storage/dump_format_v2.h"
#include "storage/dump_source_identity.h"
#include "utils/error.h"

namespace {

using mygram::utils::ErrorCode;
using mygramdb::index::Index;
using mygramdb::storage::DocumentStore;
using mygramdb::storage::FilterValue;

namespace corpus = mygramdb::compat;

/// Read a checked-in fixture verbatim. Never writes, never regenerates.
std::string ReadFixture(std::string_view name) {
  const std::filesystem::path path = std::filesystem::path(MYGRAMDB_COMPAT_CORPUS_DIR) / std::string(name);
  std::ifstream stream(path, std::ios::binary);
  EXPECT_TRUE(stream) << "missing corpus fixture: " << path;
  return std::string((std::istreambuf_iterator<char>(stream)), std::istreambuf_iterator<char>());
}

std::string FixturePath(std::string_view name) {
  return (std::filesystem::path(MYGRAMDB_COMPAT_CORPUS_DIR) / std::string(name)).string();
}

/// A table's restore targets, kept together so a load can be asserted on both.
struct RestoreTargets {
  std::unique_ptr<Index> index;
  std::unique_ptr<DocumentStore> doc_store;

  std::unordered_map<std::string, std::pair<Index*, DocumentStore*>> Contexts(std::string_view table_name) {
    std::unordered_map<std::string, std::pair<Index*, DocumentStore*>> contexts;
    contexts.emplace(std::string(table_name), std::make_pair(index.get(), doc_store.get()));
    return contexts;
  }
};

RestoreTargets MakeCorpusTargets() {
  return RestoreTargets{corpus::MakeCorpusIndex(), std::make_unique<DocumentStore>()};
}

/// Assert the index holds exactly the terms and posting lists the corpus pins.
void ExpectCorpusIndexContent(const Index& index) {
  const auto terms = corpus::CorpusTerms();
  EXPECT_EQ(index.TermCount(), terms.size());
  for (const auto& term : terms) {
    EXPECT_EQ(index.Count(term.term), term.doc_ids.size()) << "term: " << term.term;
    EXPECT_EQ(index.SearchOr({std::string(term.term)}), term.doc_ids) << "term: " << term.term;
  }
  // A term present in two posting lists intersects to the one document in both.
  EXPECT_EQ(index.SearchAnd({"he", "ll"}), std::vector<mygramdb::DocId>({1}));
}

/**
 * @brief Assert the document store holds exactly what the corpus pins.
 *
 * @param store Loaded store
 * @param version Document store format version the payload declared, which
 *                decides whether per-document texts are expected at all
 */
void ExpectCorpusDocStoreContent(const DocumentStore& store, uint32_t version) {
  const auto documents = corpus::CorpusDocuments();
  ASSERT_EQ(store.Size(), documents.size());

  for (const auto& document : documents) {
    EXPECT_EQ(store.GetDocId(document.primary_key), std::optional<mygramdb::DocId>(document.doc_id));
    EXPECT_EQ(store.GetPrimaryKey(document.doc_id), std::optional<std::string>(std::string(document.primary_key)));

    if (version >= 2) {
      EXPECT_EQ(store.GetNormalizedText(document.doc_id),
                std::optional<std::string>(std::string(document.normalized_text)));
    } else {
      EXPECT_FALSE(store.GetNormalizedText(document.doc_id).has_value());
    }
    if (version >= 3) {
      EXPECT_EQ(store.GetOriginalText(document.doc_id),
                std::optional<std::string>(std::string(document.original_text)));
    } else {
      EXPECT_FALSE(store.GetOriginalText(document.doc_id).has_value());
    }
  }

  const auto int_filter = store.GetFilterValue(1, corpus::kIntFilterName);
  ASSERT_TRUE(int_filter.has_value());
  ASSERT_TRUE(std::holds_alternative<int32_t>(*int_filter));
  EXPECT_EQ(std::get<int32_t>(*int_filter), corpus::kIntFilterValue);

  const auto string_filter = store.GetFilterValue(2, corpus::kStringFilterName);
  ASSERT_TRUE(string_filter.has_value());
  ASSERT_TRUE(std::holds_alternative<std::string>(*string_filter));
  EXPECT_EQ(std::get<std::string>(*string_filter), corpus::kStringFilterValue);

  EXPECT_FALSE(store.GetFilterValue(3, corpus::kIntFilterName).has_value());
  EXPECT_FALSE(store.GetFilterValue(3, corpus::kStringFilterName).has_value());
}

// ============================================================================
// Index payloads
// ============================================================================

struct IndexFixture {
  std::string_view file;
  uint32_t version;
};

class IndexPayloadCorpusTest : public ::testing::TestWithParam<IndexFixture> {};

TEST_P(IndexPayloadCorpusTest, LoadsWithTheRecordedTerms) {
  const IndexFixture fixture = GetParam();
  std::istringstream stream(ReadFixture(fixture.file));

  auto index = corpus::MakeCorpusIndex();
  auto result = index->LoadFromStream(stream);
  ASSERT_TRUE(result.has_value()) << "index format version " << fixture.version
                                  << " is no longer readable: " << result.error().message();
  ExpectCorpusIndexContent(*index);
}

INSTANTIATE_TEST_SUITE_P(AcceptedVersions, IndexPayloadCorpusTest,
                         ::testing::Values(IndexFixture{corpus::kIndexV1File, 1}, IndexFixture{corpus::kIndexV2File, 2},
                                           IndexFixture{corpus::kIndexV3File, 3},
                                           IndexFixture{corpus::kIndexV4File, 4}),
                         [](const ::testing::TestParamInfo<IndexFixture>& info) {
                           return "V" + std::to_string(info.param.version);
                         });

TEST(IndexPayloadCorpusRejectionTest, VersionAboveTheCeilingIsRefused) {
  std::istringstream stream(ReadFixture(corpus::kIndexV5File));
  auto index = corpus::MakeCorpusIndex();

  auto result = index->LoadFromStream(stream);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageVersionMismatch);
  EXPECT_NE(result.error().message().find("Unsupported index format version"), std::string::npos);
}

// ============================================================================
// Document store payloads
// ============================================================================

struct DocStoreFixture {
  std::string_view file;
  uint32_t version;
};

class DocStorePayloadCorpusTest : public ::testing::TestWithParam<DocStoreFixture> {};

TEST_P(DocStorePayloadCorpusTest, LoadsWithTheRecordedDocuments) {
  const DocStoreFixture fixture = GetParam();
  std::istringstream stream(ReadFixture(fixture.file));

  DocumentStore store;
  std::string gtid;
  auto result = store.LoadFromStream(stream, &gtid);
  ASSERT_TRUE(result.has_value()) << "document store format version " << fixture.version
                                  << " is no longer readable: " << result.error().message();
  EXPECT_EQ(gtid, corpus::kGtid);
  ExpectCorpusDocStoreContent(store, fixture.version);
}

INSTANTIATE_TEST_SUITE_P(AcceptedVersions, DocStorePayloadCorpusTest,
                         ::testing::Values(DocStoreFixture{corpus::kDocStoreV1File, 1},
                                           DocStoreFixture{corpus::kDocStoreV2File, 2},
                                           DocStoreFixture{corpus::kDocStoreV3File, 3}),
                         [](const ::testing::TestParamInfo<DocStoreFixture>& info) {
                           return "V" + std::to_string(info.param.version);
                         });

TEST(DocStorePayloadCorpusRejectionTest, VersionAboveTheCeilingIsRefused) {
  std::istringstream stream(ReadFixture(corpus::kDocStoreV4File));

  DocumentStore store;
  auto result = store.LoadFromStream(stream);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageCorrupted);
  EXPECT_NE(result.error().message().find("Unsupported document store file version"), std::string::npos);
}

// ============================================================================
// Dump containers
// ============================================================================

struct DumpFixture {
  std::string_view file;
  const char* name;
  /// Document store version embedded in the table section.
  uint32_t docstore_version;
  /// Whether the dump records a MySQL source server UUID at all.
  bool records_source_server_uuid;
  /// UUID the dump is expected to yield when it records one.
  std::string_view source_server_uuid;
  /// memory.verify_text the config section is expected to yield.
  std::string_view verify_text;
};

class DumpContainerCorpusTest : public ::testing::TestWithParam<DumpFixture> {};

TEST_P(DumpContainerCorpusTest, LoadsWithTheRecordedContent) {
  const DumpFixture fixture = GetParam();

  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);

  std::string gtid;
  mygramdb::config::Config loaded_config;
  mygramdb::storage::DumpSourceIdentity source_identity;

  auto result = mygramdb::storage::dump_v2::ReadDump(FixturePath(fixture.file), gtid, loaded_config, contexts, nullptr,
                                                     nullptr, nullptr, {}, {}, &source_identity);
  ASSERT_TRUE(result.has_value()) << fixture.name << " is no longer readable: " << result.error().message();

  EXPECT_EQ(gtid, corpus::kGtid);
  EXPECT_EQ(source_identity.recorded, fixture.records_source_server_uuid);
  EXPECT_EQ(source_identity.uuid, fixture.source_server_uuid);
  EXPECT_EQ(loaded_config.memory.verify_text, fixture.verify_text);
  EXPECT_EQ(loaded_config.mysql.host, corpus::kMysqlHost);
  EXPECT_EQ(loaded_config.mysql.port, corpus::kMysqlPort);
  EXPECT_EQ(loaded_config.mysql.database, corpus::kMysqlDatabase);
  ASSERT_EQ(loaded_config.tables.size(), 1U);
  EXPECT_EQ(loaded_config.tables[0].name, corpus::kTableName);
  EXPECT_EQ(loaded_config.tables[0].ngram_size, corpus::kNgramSize);
  EXPECT_EQ(loaded_config.tables[0].kanji_ngram_size, corpus::kKanjiNgramSize);

  ExpectCorpusIndexContent(*targets.index);
  ExpectCorpusDocStoreContent(*targets.doc_store, fixture.docstore_version);
}

INSTANTIATE_TEST_SUITE_P(
    AcceptedVersions, DumpContainerCorpusTest,
    ::testing::Values(
        // Container V1, compatibility metadata version 1, index V1, docstore V1.
        DumpFixture{corpus::kDumpV1MetaV1File, "container V1 with compatibility metadata version 1", 1, false, "",
                    corpus::kVerifyText},
        // Container V1 as WriteDumpV1 emits it: metadata version 2, index V4, docstore V3.
        DumpFixture{corpus::kDumpV1MetaV2File, "container V1 from WriteDumpV1", 3, false, "", corpus::kVerifyText},
        // Container V2 carrying index V3 and docstore V2, versions no writer emits.
        DumpFixture{corpus::kDumpV2LegacyPayloadsFile, "container V2 with legacy embedded payloads", 2, true,
                    corpus::kSourceServerUuid, corpus::kVerifyText},
        // Container V2 as WriteDumpV2 emits it.
        DumpFixture{corpus::kDumpV2CurrentFile, "container V2 from WriteDumpV2", 3, true, corpus::kSourceServerUuid,
                    corpus::kVerifyText}),
    [](const ::testing::TestParamInfo<DumpFixture>& info) {
      std::string suite_name(info.param.file);
      suite_name = suite_name.substr(0, suite_name.find('.'));
      for (char& character : suite_name) {
        if (character == '_') {
          character = 'X';
        }
      }
      return suite_name;
    });

TEST(DumpContainerCorpusRejectionTest, VersionAboveTheCeilingIsRefused) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result = mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV3File), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageDumpReadError);
  EXPECT_NE(result.error().message().find("Unsupported dump version"), std::string::npos);
}

TEST(DumpContainerCorpusRejectionTest, CompatibilityMetadataVersionAboveTheCeilingIsRefused) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result =
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpMetaV3File), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageVersionMismatch);
  EXPECT_NE(result.error().message().find("Unsupported compatibility metadata version"), std::string::npos);
}

TEST(DumpContainerCorpusRejectionTest, DirectV2ReaderRefusesAV1Container) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result =
      mygramdb::storage::dump_v2::ReadDumpV2(FixturePath(corpus::kDumpV1MetaV1File), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageDumpReadError);
  EXPECT_NE(result.error().message().find("Not a V2 dump file"), std::string::npos);
}

TEST(DumpContainerCorpusRejectionTest, DirectV1ReaderRefusesAV2Container) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result =
      mygramdb::storage::dump_v1::ReadDumpV1(FixturePath(corpus::kDumpV2CurrentFile), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageVersionMismatch);
}

// ============================================================================
// The source-identity rule both restore paths apply
// ============================================================================

/// Restore a fixture and hand its recorded source to the shared policy.
mygram::utils::Expected<void, mygram::utils::Error> LoadUnderSourcePolicy(
    std::string_view fixture, const std::string& live_source_server_uuid, RestoreTargets& targets,
    mygramdb::storage::DumpSourceIdentity& source_identity) {
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto validator = [&source_identity, &live_source_server_uuid](
                       const mygramdb::config::Config&,
                       const std::string&) -> mygram::utils::Expected<void, mygram::utils::Error> {
    if (auto mismatch = mygramdb::storage::FindDumpSourceIdentityMismatch(source_identity, live_source_server_uuid);
        mismatch.has_value()) {
      return mygram::utils::MakeUnexpected(
          mygram::utils::MakeError(ErrorCode::kStorageVersionMismatch, std::string(mismatch->detail)));
    }
    return {};
  };

  return mygramdb::storage::dump_v2::ReadDump(FixturePath(fixture), gtid, loaded_config, contexts, nullptr, nullptr,
                                              nullptr, validator, {}, &source_identity);
}

TEST(DumpSourceIdentityTest, AV1ContainerRecordsNoSourceServerUuid) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;
  mygramdb::storage::DumpSourceIdentity source_identity;

  auto result = mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV1MetaV1File), gtid, loaded_config,
                                                     contexts, nullptr, nullptr, nullptr, {}, {}, &source_identity);
  ASSERT_TRUE(result.has_value()) << result.error().message();
  // The V1 container has no field for it, so the source stays unknown rather
  // than coming back as an empty UUID.
  EXPECT_FALSE(source_identity.recorded);
  EXPECT_TRUE(source_identity.uuid.empty());
}

TEST(DumpSourceIdentityTest, ADumpThatRecordsNoSourceServerUuidIsAccepted) {
  auto targets = MakeCorpusTargets();
  mygramdb::storage::DumpSourceIdentity source_identity;

  auto result = LoadUnderSourcePolicy(corpus::kDumpV1MetaV1File, std::string(corpus::kSourceServerUuid), targets,
                                      source_identity);
  ASSERT_TRUE(result.has_value()) << result.error().message();
  EXPECT_FALSE(source_identity.recorded);
  ExpectCorpusIndexContent(*targets.index);
}

TEST(DumpSourceIdentityTest, ADumpRecordingTheRunningSourceIsAccepted) {
  auto targets = MakeCorpusTargets();
  mygramdb::storage::DumpSourceIdentity source_identity;

  auto result = LoadUnderSourcePolicy(corpus::kDumpV2CurrentFile, std::string(corpus::kSourceServerUuid), targets,
                                      source_identity);
  ASSERT_TRUE(result.has_value()) << result.error().message();
  EXPECT_TRUE(source_identity.recorded);
  EXPECT_EQ(source_identity.uuid, corpus::kSourceServerUuid);
}

TEST(DumpSourceIdentityTest, ADumpRecordingADifferentSourceIsRefused) {
  auto targets = MakeCorpusTargets();
  mygramdb::storage::DumpSourceIdentity source_identity;

  auto result = LoadUnderSourcePolicy(corpus::kDumpV2CurrentFile, "11111111-2222-3333-4444-555555555555", targets,
                                      source_identity);
  ASSERT_FALSE(result.has_value()) << "widening the unknown case must not widen the mismatched one";
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageVersionMismatch);
  EXPECT_NE(result.error().message().find("source server UUID does not match"), std::string::npos)
      << result.error().message();

  // The refusal happens before any live table state is replaced.
  EXPECT_EQ(targets.index->TermCount(), 0U);
  EXPECT_EQ(targets.doc_store->Size(), 0U);
}

TEST(DumpSourceIdentityTest, PolicyDistinguishesAnUnknownSourceFromAnEmptyRecordedOne) {
  const std::string live_source = "3e11fa47-71ca-11e1-9e33-c80aa9429562";

  // Nothing recorded: the artifact makes no claim, so there is nothing to
  // disagree with.
  EXPECT_FALSE(mygramdb::storage::FindDumpSourceIdentityMismatch(mygramdb::storage::DumpSourceIdentity{}, live_source)
                   .has_value());

  // Recorded as empty: the dump was taken with no binlog reader attached, and
  // that is still refused.
  const auto empty_recorded =
      mygramdb::storage::FindDumpSourceIdentityMismatch(mygramdb::storage::DumpSourceIdentity{true, ""}, live_source);
  ASSERT_TRUE(empty_recorded.has_value());
  EXPECT_NE(std::string(empty_recorded->detail).find("does not record its MySQL source server UUID"),
            std::string::npos);

  // The running server's own source unknown: no comparison is possible.
  EXPECT_FALSE(mygramdb::storage::FindDumpSourceIdentityMismatch(
                   mygramdb::storage::DumpSourceIdentity{true, "some-other-server"}, "")
                   .has_value());
}

// ============================================================================
// Configuration compatibility of the loaded config sections
// ============================================================================

TEST(DumpConfigCompatibilityTest, MetadataBearingDumpMatchesAServerRunningTheSameSettings) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  ASSERT_TRUE(
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV2CurrentFile), gtid, loaded_config, contexts)
          .has_value());

  const auto live_config = corpus::CorpusConfig();
  EXPECT_FALSE(mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config).has_value());
}

// The table-scoped settings are only reached once the dump's table resolves to a
// running-config entry, and resolution is by qualified name. A fixture whose
// table carried no database would resolve to nothing and skip these comparisons
// instead of making them, which the test above cannot distinguish from a match.
TEST(DumpConfigCompatibilityTest, DivergingNgramSizeIsRefusedByTheSharedCheck) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  ASSERT_TRUE(
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV2CurrentFile), gtid, loaded_config, contexts)
          .has_value());

  auto live_config = corpus::CorpusConfig();
  ASSERT_FALSE(live_config.tables.empty());
  live_config.tables[0].ngram_size = corpus::kNgramSize + 1;
  const auto mismatch = mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config);
  ASSERT_TRUE(mismatch.has_value()) << "the dump table must resolve to the running entry and be compared";
  EXPECT_NE(mismatch->find("ngram_size mismatch"), std::string::npos) << *mismatch;
  EXPECT_NE(mismatch->find(std::string(corpus::kMysqlDatabase) + "." + std::string(corpus::kTableName)),
            std::string::npos)
      << *mismatch;
}

TEST(DumpConfigCompatibilityTest, DivergingNormalizationIsRefusedByTheSharedCheck) {
  auto targets = MakeCorpusTargets();
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  ASSERT_TRUE(
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kDumpV2CurrentFile), gtid, loaded_config, contexts)
          .has_value());

  auto live_config = corpus::CorpusConfig();
  live_config.memory.normalize.lower = !corpus::kNormalizeLower;
  const auto mismatch = mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config);
  ASSERT_TRUE(mismatch.has_value());
  EXPECT_NE(mismatch->find("memory.normalize.lower"), std::string::npos);
}

// ============================================================================
// Dumps written by earlier releases
//
// These four files came out of the release trees named in their file names,
// through that release's own dump writer, so they carry that release's
// defaults rather than the manifest's settings. They are the only fixtures in
// the corpus whose bytes no current code path can reproduce.
// ============================================================================

struct ReleaseDumpFixture {
  std::string_view file;
  const char* release;
  /// memory.verify_text the config section yields. Releases that predate the
  /// compatibility metadata record nothing, which reads back as empty.
  std::string_view verify_text;
  /// Whether the document store payload carries per-document normalized text.
  bool has_normalized_text;
};

class ReleaseDumpCorpusTest : public ::testing::TestWithParam<ReleaseDumpFixture> {};

TEST_P(ReleaseDumpCorpusTest, StillLoadsWithItsRecordedContent) {
  const ReleaseDumpFixture fixture = GetParam();

  // Every one of these releases wrote its index payload from a default-
  // configured Index, so the restore target has to be one too.
  RestoreTargets targets{std::make_unique<Index>(), std::make_unique<DocumentStore>()};
  auto contexts = targets.Contexts(corpus::kTableName);

  std::string gtid;
  mygramdb::config::Config loaded_config;
  mygramdb::storage::DumpSourceIdentity source_identity;

  auto result = mygramdb::storage::dump_v2::ReadDump(FixturePath(fixture.file), gtid, loaded_config, contexts, nullptr,
                                                     nullptr, nullptr, {}, {}, &source_identity);
  ASSERT_TRUE(result.has_value()) << "a dump written by " << fixture.release
                                  << " is no longer readable: " << result.error().message();

  EXPECT_EQ(gtid, corpus::kGtid);
  EXPECT_EQ(loaded_config.mysql.host, corpus::kMysqlHost);
  EXPECT_EQ(loaded_config.mysql.port, corpus::kMysqlPort);
  EXPECT_EQ(loaded_config.mysql.database, corpus::kMysqlDatabase);
  ASSERT_EQ(loaded_config.tables.size(), 1U);
  EXPECT_EQ(loaded_config.tables[0].name, corpus::kTableName);
  EXPECT_EQ(loaded_config.tables[0].ngram_size, 2);
  EXPECT_EQ(loaded_config.memory.verify_text, fixture.verify_text);

  // No release up to and including v1.9.0 recorded a MySQL source server UUID.
  EXPECT_FALSE(source_identity.recorded);

  // The three indexed documents were "hello", "hello world" and "helo".
  EXPECT_EQ(targets.index->SearchOr({"he"}), std::vector<mygramdb::DocId>({1, 2, 3}));
  EXPECT_EQ(targets.index->SearchOr({"ll"}), std::vector<mygramdb::DocId>({1, 2}));
  EXPECT_EQ(targets.index->SearchOr({"wo"}), std::vector<mygramdb::DocId>({2}));
  EXPECT_EQ(targets.index->SearchAnd({"he", "wo"}), std::vector<mygramdb::DocId>({2}));

  ASSERT_EQ(targets.doc_store->Size(), 3U);
  EXPECT_EQ(targets.doc_store->GetDocId("alpha"), std::optional<mygramdb::DocId>(1));
  EXPECT_EQ(targets.doc_store->GetDocId("beta"), std::optional<mygramdb::DocId>(2));
  EXPECT_EQ(targets.doc_store->GetDocId("gamma"), std::optional<mygramdb::DocId>(3));
  EXPECT_EQ(targets.doc_store->GetPrimaryKey(2), std::optional<std::string>("beta"));

  if (fixture.has_normalized_text) {
    EXPECT_EQ(targets.doc_store->GetNormalizedText(2), std::optional<std::string>("hello world"));
  } else {
    EXPECT_FALSE(targets.doc_store->GetNormalizedText(2).has_value());
  }
}

INSTANTIATE_TEST_SUITE_P(EarlierReleases, ReleaseDumpCorpusTest,
                         ::testing::Values(ReleaseDumpFixture{corpus::kReleaseV154File, "v1.5.4", "", false},
                                           ReleaseDumpFixture{corpus::kReleaseV161File, "v1.6.1", "", false},
                                           ReleaseDumpFixture{corpus::kReleaseV190File, "v1.9.0", corpus::kVerifyText,
                                                              true}),
                         [](const ::testing::TestParamInfo<ReleaseDumpFixture>& info) {
                           std::string name(info.param.release);
                           for (char& character : name) {
                             if (character == '.') {
                               character = '_';
                             }
                           }
                           return name;
                         });

/**
 * @brief A dump written by v1.3.2 stops inside its index payload.
 *
 * Its container header, its config section and its document store payload all
 * decode. Its posting lists do not: that release wrote the posting list's
 * strategy byte, element count and delta values with the octets in the reverse
 * order to every later release, and nothing in the artifact records which order
 * was used, so the decoder cannot tell one from the other.
 *
 * This assertion states what the code does today, not that the behavior is
 * right. If the posting list decoder is ever taught to read that byte order,
 * this test is the thing that has to change.
 */
TEST(ReleaseDumpCorpusRejectionTest, DumpWrittenByV132IsRefusedForItsPostingListByteOrder) {
  RestoreTargets targets{std::make_unique<Index>(), std::make_unique<DocumentStore>()};
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result =
      mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kReleaseV132File), gtid, loaded_config, contexts);
  ASSERT_FALSE(result.has_value()) << "a v1.3.2 dump now loads; the corpus expectation is stale";
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageDumpReadError);
  // The refusal names the index payload, which is only reached once the header
  // and the config section have decoded.
  EXPECT_NE(result.error().message().find("LoadFromStream failed for index"), std::string::npos)
      << "unexpected refusal reason: " << result.error().message();

  // Nothing was applied to the live objects.
  EXPECT_EQ(targets.index->TermCount(), 0U);
  EXPECT_EQ(targets.doc_store->Size(), 0U);
}

/**
 * @brief The zero header_size those releases left behind is not corruption.
 *
 * Releases up to and including v1.5.3 wrote the V1 header's header_size field
 * as a literal zero and never patched it, so zero is the marker such a release
 * leaves rather than a wrong length. Any other value still has to be exact.
 */
TEST(ReleaseDumpCorpusTest, ZeroHeaderSizeIsAcceptedButAWrongOneIsNot) {
  std::string bytes = ReadFixture(corpus::kReleaseV132File);
  // File offset 8 is the V1 header_size field (spec/persistence-formats.md 1.2).
  ASSERT_GT(bytes.size(), 12U);
  bytes[8] = 0x7F;

  const std::filesystem::path scratch =
      std::filesystem::temp_directory_path() / "mygramdb_corpus_wrong_header_size.dmp";
  {
    std::ofstream out(scratch, std::ios::binary | std::ios::trunc);
    ASSERT_TRUE(out);
    out.write(bytes.data(), static_cast<std::streamsize>(bytes.size()));
  }

  RestoreTargets targets{std::make_unique<Index>(), std::make_unique<DocumentStore>()};
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  auto result = mygramdb::storage::dump_v2::ReadDump(scratch.string(), gtid, loaded_config, contexts);
  std::filesystem::remove(scratch);

  ASSERT_FALSE(result.has_value());
  EXPECT_EQ(result.error().code(), ErrorCode::kStorageDumpReadError);
  EXPECT_NE(result.error().message().find("Invalid V1 header size"), std::string::npos)
      << "unexpected refusal reason: " << result.error().message();

  // Nothing was applied to the live objects.
  EXPECT_EQ(targets.index->TermCount(), 0U);
  EXPECT_EQ(targets.doc_store->Size(), 0U);
}

TEST(ReleaseDumpConfigCompatibilityTest, DumpsPredatingCompatibilityMetadataLoadOnlyIntoVerifyTextOff) {
  RestoreTargets targets{std::make_unique<Index>(), std::make_unique<DocumentStore>()};
  auto contexts = targets.Contexts(corpus::kTableName);
  std::string gtid;
  mygramdb::config::Config loaded_config;

  ASSERT_TRUE(mygramdb::storage::dump_v2::ReadDump(FixturePath(corpus::kReleaseV154File), gtid, loaded_config, contexts)
                  .has_value());
  ASSERT_TRUE(loaded_config.memory.verify_text.empty());

  // Isolate the verify_text rule: everything else the shared check compares is
  // taken from the dump, so only the missing metadata can cause a mismatch.
  auto live_config = loaded_config;
  live_config.memory.verify_text = "off";
  EXPECT_FALSE(mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config).has_value());

  live_config.memory.verify_text = "all";
  const auto mismatch = mygramdb::server::FindDumpConfigMismatch(loaded_config, live_config);
  ASSERT_TRUE(mismatch.has_value());
  EXPECT_NE(mismatch->find("verify_text"), std::string::npos);
}

}  // namespace
