# CMake script to embed JSON Schema as C++ header
# Usage: cmake -P EmbedSchema.cmake

# Read the JSON schema file
file(READ "${INPUT_FILE}" SCHEMA_CONTENT)

# Escape special characters for C++ string literal
string(REPLACE "\\" "\\\\" SCHEMA_CONTENT "${SCHEMA_CONTENT}")
string(REPLACE "\"" "\\\"" SCHEMA_CONTENT "${SCHEMA_CONTENT}")
string(REPLACE "\n" "\\n" SCHEMA_CONTENT "${SCHEMA_CONTENT}")

# Generate C++ header file
file(WRITE "${OUTPUT_FILE}" "/**
 * @file config_schema_embedded.h
 * @brief Embedded JSON Schema for configuration validation
 *
 * This file is auto-generated by CMake from config-schema.json
 * DO NOT EDIT MANUALLY
 */

#pragma once

#include <string_view>

namespace mygramdb {
namespace config {

// Embedded JSON Schema
constexpr std::string_view kConfigSchemaJson = R\"SCHEMA(
${SCHEMA_CONTENT}
)SCHEMA\";

}  // namespace config
}  // namespace mygramdb
")

message(STATUS "Embedded schema generated: ${OUTPUT_FILE}")
